version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/test/integration"
  groups:
    minor-and-patch:
      applies-to: version-updates
      update-types:
      - "minor"
      - "patch"
    major-updates:
      applies-to: version-updates
      update-types:
      - "major"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 2
- package-ecosystem: "terraform"
  directory: "/"
  groups:
    minor-and-patch:
      applies-to: version-updates
      update-types:
      - "minor"
      - "patch"
    major-updates:
      applies-to: version-updates
      update-types:
      - "major"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 2