---
version: 2
updates:
- package-ecosystem: "gomod"
  directories:
    - /test/integration
  groups:
    minor-and-patch:
      applies-to: version-updates
      update-types:
      - "minor"
      - "patch"
  schedule:
    interval: "weekly"
    time: "09:00"
    timezone: "Europe/Oslo"
    day: "monday"
  open-pull-requests-limit: 2
- package-ecosystem: "github-actions"
  directories:
    - /
  groups:
    minor-and-patch:
      applies-to: version-updates
      update-types:
      - "minor"
      - "patch"
  schedule:
    interval: "weekly"
    time: "09:00"
    timezone: "Europe/Oslo"
    day: "monday"
  open-pull-requests-limit: 2
- package-ecosystem: terraform
  directories:
  - /examples/*
  - /test/fixtures/*
  schedule:
    interval: "daily"
    time: "09:00"
    timezone: "Europe/Oslo"
  open-pull-requests-limit: 0  # Security-updates only
- package-ecosystem: terraform
  directories:
  - /modules/*
  schedule:
    interval: "daily"
    time: "09:00"
    timezone: "Europe/Oslo"
  open-pull-requests-limit: 0  # Security-updates only
  commit-message:
    prefix: "fix(deps):" # trigger new release when updating user-facing modules  
