name: Checkov Scan

on:
  push:
  pull_request:
    paths:
      - 'modules/postgresql/**'
      - 'test/**'
    branches:
      - master
    types:
      - opened
      - synchronize
      - ready_for_review
  workflow_dispatch:

jobs:
  scan:
    permissions:
      contents: 'read'
      security-events: 'write'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.0
          terraform_wrapper: false
      - name: Run Checkov action
        id: checkov
        #continue-on-error: true # alternative to use soft_fail in with clause
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: modules/postgresql
          repo_root_for_plan_enrichment: examples/minimal_test
          log_level: INFO
          soft_fail: true
          framework: terraform
          output_format: cli,sarif
          output_file_path: console,results.sarif
          download_external_modules: true
          #check: CKV_GCP_110,CKV_GCP_52  # optional: run only a specific check_id. can be comma separated list
          skip_check: CKV_GCP_56 # optional: skip a specific check_id. can be comma separated list
          

      - name: Upload Checkov SARIF results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif