name: Call Terraform Tests, Docs & Compliance

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - ready_for_review

jobs:
  tf-lint-postgresql:
    name: Terraform Lint PostgreSQL
    uses: entur/gha-terraform/.github/workflows/lint.yml@v1
    with:
      directory: "./modules/postgresql"
      version: 1.8.5
  tf-lint-postgresql-replica:
    name: Terraform Lint PostgreSQL Replica
    uses: entur/gha-terraform/.github/workflows/lint.yml@v1
    with:
      directory: "./modules/postgresql-replica"
      version: 1.8.5
  tf-lint-minimal_test:
    name: Terraform Lint Examples
    uses: entur/gha-terraform/.github/workflows/lint.yml@v1
    with:
      directory: "./examples/minimal_test"
      version: 1.8.5
