name: Call Terraform Tests, Docs & Compliance

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - ready_for_review

jobs:
  tf-lint-postgresql:
    name: Terraform Lint PostgreSQL
    uses: entur/gha-terraform/.github/workflows/lint.yml@v1
    with:
      directory: "./modules/postgresql"
      version: 1.8.5
  tf-lint-postgresql-replica:
    name: Terraform Lint PostgreSQL Replica
    uses: entur/gha-terraform/.github/workflows/lint.yml@v1
    with:
      directory: "./modules/postgresql-replica"
      version: 1.8.5

  docs:
    runs-on: ubuntu-24.04
    name: Render Terraform Docs
    needs: [tf-lint-postgresql, tf-lint-postgresql-replica]
    strategy:
      matrix:
        dir:
          - modules/postgresql
          - modules/postgresql-replica
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Render terraform docs inside the README.md and push changes back to PR branch
        uses: terraform-docs/gh-actions@aeae0038ed47a547e0c0fca5c059d3335f48fb25 # v1.3.0
        with:
          working-dir: ${{ matrix.dir }}
          output-file: README.md
          output-method: inject
          git-push: "true"
