name: Call Validate PR

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited

jobs:
  validate-pr:
    name: Ensure PR title complies with conventional commit conventions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231 # v6.0.2

      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
