name: release
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses: entur/gha-meta/.github/workflows/release.yml@v1
